### ISSUE TITLE
rake aborted！ error: cannot run test program while cross compiling

### ISSUE THREAD

**Issue by fzq2016** [shaojiankui/samba-iOS#1]
按你的方法替换了smaba文件，重新rake之后，编译出现如下错误哦：

checking byteswap.h presence... no
checking for byteswap.h... no
checking whether we can compile with __attribute__((cold))... yes
checking whether we can compile with __attribute__((const))... yes
checking whether we can compile with __attribute__((noreturn))... yes
checking whether we can compile with __attribute__((printf))... yes
checking whether we can compile with __attribute__((unused))... yes
checking whether we can compile with __attribute__((used))... yes
checking whether we are big endian... configure: error: in `/Users/felix/Desktop/Felix/kxsmb/samba/source3':
**configure: error: cannot run test program while cross compiling**
See `config.log' for more details
rake aborted!
******** Build failed ********
/Users/felix/Desktop/Felix/kxsmb/Rakefile:42:in `system_or_exit'
/Users/felix/Desktop/Felix/kxsmb/Rakefile:216:in `buildArch'
/Users/felix/Desktop/Felix/kxsmb/Rakefile:260:in `block in <top (required)>'
/Users/felix/.rvm/gems/ruby-2.6.0-preview2@global/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => default => build_all => build_smb_i386
(See full trace by running task with --trace)

**Comment by bortka** [comment]
Did you ever figure out a solution to this error? I am getting the same thing.
